# Generated by Django 4.2.11 on 2024-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('acceso', models.CharField(choices=[('0', 'entrada'), ('1', 'salida')], max_length=20)),
                ('vehiculo', models.CharField(choices=[('M', 'moto'), ('A', 'Auto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
